name: build product

on:
  pull_request:
    branches:
      - main
  
  workflow_dispatch:
    inputs:
      GIT_BASE_REF:
        description: Merge base branch to compare changes with. By default only single HEAD commit is analysed for changes.
        default: ""

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.components.outputs.components }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # At least two commits are required to get changed files from last commit.
          # fetch-depth: ${{ github.event_name == 'pull_request' && 0 || 2 }}
          fetch-depth: 0

      - name: Get changed components
        id: components
        env:
          GIT_BASE_REF: ${{ github.event_name == 'pull_request' && github.base_ref || format('origin/{0}', inputs.GIT_BASE_REF) }}
        run: |
          chmod +x scripts/get_changed_components.sh
          components=$(scripts/get_changed_components.sh ${GIT_BASE_REF:+--git-base-ref $GIT_BASE_REF} --verbose)
          echo "components=$(jq --compact-output --null-input '$ARGS.positional' --args ${components[@]})" | tee -a "$GITHUB_OUTPUT"
  iac:
    needs:
      - changes
    if: contains(needs.changes.outputs.components, 'iac')
    uses: ./.github/workflows/build_component.yaml

  connectivity:
    needs:
      - changes
      - iac
    # Run if needs (dependency) are succedeed or if dependencies are skipped but there are changes in component itself.
    if: success() || (contains(needs.changes.outputs.components, 'connectivity') && needs.iac.result == 'skipped') 
    uses: ./.github/workflows/build_component.yaml
  
  aks:
    needs:
      - changes
      - iac
      - connectivity
    if: success() || (contains(needs.changes.outputs.components, 'aks') && (needs.iac.result == 'skipped' || needs.connectivity.result == 'skipped'))
    uses: ./.github/workflows/build_component.yaml
