name: build product

on:
  pull_request:
    branches:
      - main
  
  workflow_dispatch:
    inputs:
      GIT_BASE_REF:
        description: Merge base branch to compare changes with. By default only single HEAD commit is analysed for changes.
        default: ""

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.components.outputs.components }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # At least two commits are required to get changed files from last commit.
          fetch-depth: ${{ (github.event_name == 'pull_request' || inputs.GIT_BASE_REF != '') && '0' || '2' }}  # Without quotes around numbers always return 2 

      - name: Get changed components
        id: components
        env:
          GIT_BASE_REF: ${{ github.event_name == 'pull_request' && github.base_ref || inputs.GIT_BASE_REF }}
        run: |
          chmod +x scripts/get_changed_components.sh
          components=$(scripts/get_changed_components.sh ${GIT_BASE_REF:+--git-base-ref origin/$GIT_BASE_REF} --verbose)
          echo "components=$(jq --compact-output --null-input '$ARGS.positional' --args ${components[@]})" | tee -a "$GITHUB_OUTPUT"

  tags:
    needs:
      - changes
    if: contains(needs.changes.outputs.components, 'tags')
    uses: ./.github/workflows/build_component.yaml

  iac:
    needs:
      - changes
    if: contains(needs.changes.outputs.components, 'iac')
    uses: ./.github/workflows/build_component.yaml

  connectivity:
    needs:
      - changes
      - tags
      - iac
    # Run if needs (dependency) are succedeed or if dependencies are skipped but there are changes in component itself.
    if: success() || (contains(needs.changes.outputs.components, 'connectivity') && (needs.tags.result == 'skipped' || needs.iac.result == 'skipped'))
    uses: ./.github/workflows/build_component.yaml
  
  aks:
    needs:
      - changes
      - tags
      - iac
      - connectivity
    if: success() || (contains(needs.changes.outputs.components, 'aks') && (needs.tags.result == 'skipped' || needs.iac.result == 'skipped' || needs.connectivity.result == 'skipped'))
    uses: ./.github/workflows/build_component.yaml
