name: deploy environment

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
    inputs:
      GIT_BASE_REF:
        description: "Merge base branch to compare changes with. By default only single HEAD commit is analysed for changes."
        default: ""
      environment:
        description: "Delivery environment name."
        default: dev_weu

permissions:
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.components.outputs.components }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # At least two commits are required to get changed files from last commit.
          fetch-depth: ${{ inputs.GIT_BASE_REF != '' && '0' || '2' }}  # Without quotes around numbers always return 2 

      - name: Get changed components
        id: components
        env:
          GIT_BASE_REF: ${{ inputs.GIT_BASE_REF }}
        run: |
          chmod +x scripts/get_changed_components.sh
          components=$(scripts/get_changed_components.sh ${GIT_BASE_REF:+--git-base-ref origin/$GIT_BASE_REF} --verbose)
          echo "components=$(jq --compact-output --null-input '$ARGS.positional' --args ${components[@]})" | tee -a "$GITHUB_OUTPUT"
  
  iac:
    needs:
      - changes
    if: contains(needs.changes.outputs.components, 'iac')
    secrets: inherit
    uses: ./.github/workflows/deploy_component.yaml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev_weu' }}
      component: "iac"

  tags:
    needs:
      - changes
      - iac
    if: success() || (contains(needs.changes.outputs.components, 'tags') && contains('success|skipped', needs.iac.result))
    secrets: inherit
    uses: ./.github/workflows/deploy_component.yaml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev_weu' }}
      component: "tags"

  connectivity:
    needs:
      - changes
      - iac
      - tags
    if: success() || (contains(needs.changes.outputs.components, 'connectivity') && contains('success|skipped', needs.iac.result) && contains('success|skipped', needs.tags.result))
    secrets: inherit
    uses: ./.github/workflows/deploy_component.yaml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev_weu' }}
      component: "connectivity"
